// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(VemCaProfContext))]
    [Migration("20260127105522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataHoraPagamento")
                        .HasColumnType("datetime")
                        .HasColumnName("dataHoraPagamento");

                    b.Property<DateTime>("DataHorarioFinal")
                        .HasColumnType("datetime")
                        .HasColumnName("dataHorarioFinal");

                    b.Property<DateTime>("DataHorarioInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("dataHorarioInicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int")
                        .HasColumnName("idAluno");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int")
                        .HasColumnName("idDisciplina");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int")
                        .HasColumnName("idProfessor");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("int")
                        .HasColumnName("idResponsavel");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("enum('P','C','D')")
                        .HasColumnName("metodoPagamento")
                        .HasComment("P = Pix\nC = Credito\nD = Debito");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('AG','RE','PG','AP')")
                        .HasColumnName("status")
                        .HasComment("AG = Agendada\nRE = Realizada\nPG = Paga\nAP = Aguardando Pagamento\n");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDisciplina" }, "fk_Aula_Disciplina1_idx");

                    b.HasIndex(new[] { "IdResponsavel" }, "fk_Aula_Pessoa1_idx");

                    b.HasIndex(new[] { "IdProfessor" }, "fk_Aula_Pessoa2_idx");

                    b.HasIndex(new[] { "IdAluno" }, "fk_Aula_Pessoa3_idx");

                    b.ToTable("Aula", "VCP");
                });

            modelBuilder.Entity("Core.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique();

                    b.ToTable("Cidade", "VCP");
                });

            modelBuilder.Entity("Core.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nivel")
                        .HasColumnType("enum('F1','F2','M1')")
                        .HasColumnName("nivel")
                        .HasComment("F1 = Ensino Fundamental Menor\nF2 = Ensino Fundamental Maior\nM1 = Ensino Medio ");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE1");

                    b.ToTable("Disciplina", "VCP");
                });

            modelBuilder.Entity("Core.DisponibilidadeHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("date")
                        .HasColumnName("dia");

                    b.Property<TimeSpan>("HorarioFim")
                        .HasColumnType("time")
                        .HasColumnName("horarioFim");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("time")
                        .HasColumnName("horarioInicio");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int")
                        .HasColumnName("idProfessor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProfessor" }, "fk_DisponibilidadeHorario_Pessoa1_idx");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE2");

                    b.ToTable("DisponibilidadeHorario", "VCP");
                });

            modelBuilder.Entity("Core.Penalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("datetime")
                        .HasColumnName("dataHoraFim");

                    b.Property<DateTime>("DataHorarioInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("dataHorarioInicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int")
                        .HasColumnName("idProfessor");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("int")
                        .HasColumnName("idResponsavel");

                    b.Property<string>("Tipo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdProfessor" }, "fk_Penalidade_Pessoa1_idx");

                    b.HasIndex(new[] { "IdResponsavel" }, "fk_Penalidade_Pessoa2_idx");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE3");

                    b.ToTable("Penalidade", "VCP");
                });

            modelBuilder.Entity("Core.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("AlunoDeMenor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("alunoDeMenor");

                    b.Property<bool?>("Atipico")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("atipico");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("dataNascimento");

                    b.Property<string>("DescricaoProfessor")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("descricaoProfessor");

                    b.Property<byte[]>("Diploma")
                        .HasColumnType("blob")
                        .HasColumnName("diploma");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("estado");

                    b.Property<byte[]>("FotoDocumento")
                        .HasColumnType("blob")
                        .HasColumnName("fotoDocumento");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("blob")
                        .HasColumnName("fotoPerfil");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("genero");

                    b.Property<int?>("IdCidade")
                        .HasColumnType("int")
                        .HasColumnName("idCidade");

                    b.Property<bool?>("Libras")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("libras");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("numero");

                    b.Property<int?>("QuantidadeDeDependentes")
                        .HasColumnType("int")
                        .HasColumnName("quantidadeDeDependentes");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("int")
                        .HasColumnName("responsavelId");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("senha");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sobrenome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ResponsavelId" }, "FK_Pessoa_Responsavel");

                    b.HasIndex(new[] { "Cpf" }, "cpf_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "IdCidade" }, "fk_Pessoa_Cidade1_idx");

                    b.HasIndex(new[] { "Id" }, "id_UNIQUE")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE4");

                    b.ToTable("Pessoa", "VCP");
                });

            modelBuilder.Entity("DisciplinaProfessor", b =>
                {
                    b.Property<int>("IdProfessor")
                        .HasColumnType("int")
                        .HasColumnName("idProfessor");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int")
                        .HasColumnName("idDisciplina");

                    b.HasKey("IdProfessor", "IdDisciplina")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDisciplina" }, "fk_Pessoa_has_Disciplina_Disciplina1_idx");

                    b.HasIndex(new[] { "IdProfessor" }, "fk_Pessoa_has_Disciplina_Pessoa1_idx");

                    b.ToTable("Disciplina_Professor", "VCP");
                });

            modelBuilder.Entity("Core.Aula", b =>
                {
                    b.HasOne("Core.Pessoa", "IdAlunoNavigation")
                        .WithMany("AulaIdAlunoNavigations")
                        .HasForeignKey("IdAluno")
                        .IsRequired()
                        .HasConstraintName("fk_Aula_Pessoa3");

                    b.HasOne("Core.Disciplina", "IdDisciplinaNavigation")
                        .WithMany("Aulas")
                        .HasForeignKey("IdDisciplina")
                        .IsRequired()
                        .HasConstraintName("fk_Aula_Disciplina1");

                    b.HasOne("Core.Pessoa", "IdProfessorNavigation")
                        .WithMany("AulaIdProfessorNavigations")
                        .HasForeignKey("IdProfessor")
                        .IsRequired()
                        .HasConstraintName("fk_Aula_Pessoa2");

                    b.HasOne("Core.Pessoa", "IdResponsavelNavigation")
                        .WithMany("AulaIdResponsavelNavigations")
                        .HasForeignKey("IdResponsavel")
                        .IsRequired()
                        .HasConstraintName("fk_Aula_Pessoa1");

                    b.Navigation("IdAlunoNavigation");

                    b.Navigation("IdDisciplinaNavigation");

                    b.Navigation("IdProfessorNavigation");

                    b.Navigation("IdResponsavelNavigation");
                });

            modelBuilder.Entity("Core.DisponibilidadeHorario", b =>
                {
                    b.HasOne("Core.Pessoa", "IdProfessorNavigation")
                        .WithMany("DisponibilidadeHorarios")
                        .HasForeignKey("IdProfessor")
                        .IsRequired()
                        .HasConstraintName("fk_DisponibilidadeHorario_Pessoa1");

                    b.Navigation("IdProfessorNavigation");
                });

            modelBuilder.Entity("Core.Penalidade", b =>
                {
                    b.HasOne("Core.Pessoa", "IdProfessorNavigation")
                        .WithMany("PenalidadeIdProfessorNavigations")
                        .HasForeignKey("IdProfessor")
                        .IsRequired()
                        .HasConstraintName("fk_Penalidade_Pessoa1");

                    b.HasOne("Core.Pessoa", "IdResponsavelNavigation")
                        .WithMany("PenalidadeIdResponsavelNavigations")
                        .HasForeignKey("IdResponsavel")
                        .IsRequired()
                        .HasConstraintName("fk_Penalidade_Pessoa2");

                    b.Navigation("IdProfessorNavigation");

                    b.Navigation("IdResponsavelNavigation");
                });

            modelBuilder.Entity("Core.Pessoa", b =>
                {
                    b.HasOne("Core.Cidade", "IdCidadeNavigation")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdCidade")
                        .HasConstraintName("fk_Pessoa_Cidade1");

                    b.HasOne("Core.Pessoa", "Responsavel")
                        .WithMany("InverseResponsavel")
                        .HasForeignKey("ResponsavelId")
                        .HasConstraintName("FK_Pessoa_Responsavel");

                    b.Navigation("IdCidadeNavigation");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("DisciplinaProfessor", b =>
                {
                    b.HasOne("Core.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("IdDisciplina")
                        .IsRequired()
                        .HasConstraintName("fk_Pessoa_has_Disciplina_Disciplina1");

                    b.HasOne("Core.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .IsRequired()
                        .HasConstraintName("fk_Pessoa_has_Disciplina_Pessoa1");
                });

            modelBuilder.Entity("Core.Cidade", b =>
                {
                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("Core.Disciplina", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("Core.Pessoa", b =>
                {
                    b.Navigation("AulaIdAlunoNavigations");

                    b.Navigation("AulaIdProfessorNavigations");

                    b.Navigation("AulaIdResponsavelNavigations");

                    b.Navigation("DisponibilidadeHorarios");

                    b.Navigation("InverseResponsavel");

                    b.Navigation("PenalidadeIdProfessorNavigations");

                    b.Navigation("PenalidadeIdResponsavelNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
