// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CadastrarpenalidadevlidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cadastrarpenalidadevlida() {
    driver.Navigate().GoToUrl("https://localhost:7266/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) span")).Click();
    driver.FindElement(By.CssSelector(".pb-3")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".secondary-text")).Text, Is.EqualTo("Histórico de penalidades"));
    driver.FindElement(By.LinkText("Criar Nova Penalidade")).Click();
    driver.FindElement(By.Id("DataHorarioInicio")).Click();
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2027-10-20T11:05");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2027-10-20T11:50");
    driver.FindElement(By.Id("DataHoraFim")).Click();
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2027-10-28T11:05");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2027-10-28T11:50");
    driver.FindElement(By.Id("Tipo")).Click();
    driver.FindElement(By.Id("Tipo")).SendKeys("Atraso");
    driver.FindElement(By.Id("Descricao")).Click();
    driver.FindElement(By.Id("Descricao")).SendKeys("há descumprimento dos prazos");
    driver.FindElement(By.Id("IdProfessor")).Click();
    {
      var dropdown = driver.FindElement(By.Id("IdProfessor"));
      dropdown.FindElement(By.XPath("//option[. = 'João']")).Click();
    }
    driver.FindElement(By.Id("IdResponsavel")).Click();
    {
      var dropdown = driver.FindElement(By.Id("IdResponsavel"));
      dropdown.FindElement(By.XPath("//option[. = 'Roberto']")).Click();
    }
    driver.FindElement(By.CssSelector(".pb-3")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(1)")).Text, Is.EqualTo("20/10/2027 11:50"));
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(2)")).Text, Is.EqualTo("28/10/2027 11:50"));
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(3)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(3)")).Text, Is.EqualTo("Atraso"));
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(4)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(4)")).Text, Is.EqualTo("há descumprimento dos prazos"));
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(5)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(5)")).Text, Is.EqualTo("João"));
    driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(4) > td:nth-child(6)")).Text, Is.EqualTo("Roberto"));
  }
}
