// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EditarpenalidadevlidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void editarpenalidadevlida() {
    driver.Navigate().GoToUrl("https://localhost:7266/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) span")).Click();
    driver.FindElement(By.CssSelector(".pb-3")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".secondary-text")).Text, Is.EqualTo("Histórico de penalidades"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Text, Is.EqualTo("20/05/2026 08:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(2)")).Text, Is.EqualTo("20/05/2026 09:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(3)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(3)")).Text, Is.EqualTo("Advertência"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(4)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(4)")).Text, Is.EqualTo("Atraso na entrega de atividade"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(5)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(5)")).Text, Is.EqualTo("Maria"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(6)")).Text, Is.EqualTo("Carlos"));
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(1) .edit-icon"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(1) .edit-icon"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(1) .edit-icon"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(7)")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .edit-icon path")).Click();
    driver.FindElement(By.Id("DataHorarioInicio")).Click();
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2026-05-03T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2026-05-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2026-01-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2026-10-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("0002-10-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("0020-10-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("0202-10-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).SendKeys("2027-10-30T08:00");
    driver.FindElement(By.Id("DataHorarioInicio")).Click();
    driver.FindElement(By.Id("DataHoraFim")).Click();
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2026-05-01T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2026-05-12T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2026-01-12T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2026-11-12T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("0002-11-12T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("0020-11-12T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("0202-11-12T09:00");
    driver.FindElement(By.Id("DataHoraFim")).SendKeys("2027-11-12T09:00");
    driver.FindElement(By.Id("Tipo")).Click();
    driver.FindElement(By.Id("Tipo")).Click();
    driver.FindElement(By.Id("Tipo")).SendKeys("Aviso");
    driver.FindElement(By.Id("Descricao")).Click();
    driver.FindElement(By.CssSelector(".col-md-4")).Click();
    driver.FindElement(By.Id("Descricao")).SendKeys("Avaliação não foi feita");
    driver.FindElement(By.Id("IdProfessor")).Click();
    {
      var dropdown = driver.FindElement(By.Id("IdProfessor"));
      dropdown.FindElement(By.XPath("//option[. = 'Ana']")).Click();
    }
    driver.FindElement(By.Id("IdResponsavel")).Click();
    {
      var dropdown = driver.FindElement(By.Id("IdResponsavel"));
      dropdown.FindElement(By.XPath("//option[. = 'Fernanda']")).Click();
    }
    driver.FindElement(By.CssSelector(".btn-warning")).Click();
    driver.FindElement(By.CssSelector(".alert")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(1)")).Text, Is.EqualTo("30/10/2027 08:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(2)")).Text, Is.EqualTo("12/11/2027 09:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(3)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(3)")).Text, Is.EqualTo("Aviso"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(4)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(4)")).Text, Is.EqualTo("Avaliação não foi feita"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(5)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(5)")).Text, Is.EqualTo("Ana"));
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(6)")).Text, Is.EqualTo("Fernanda"));
  }
}
