// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ExcluirpenalidadevlidaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void excluirpenalidadevlida() {
    driver.Navigate().GoToUrl("https://localhost:7266/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector(".nav-item:nth-child(6) span")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(1)")).Text, Is.EqualTo("21/05/2026 10:30"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(2)")).Text, Is.EqualTo("21/05/2026 11:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Text, Is.EqualTo("Suspensão curta"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(4)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(4)")).Text, Is.EqualTo("Uso de celular em sala de aula"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(5)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(5)")).Text, Is.EqualTo("João"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(6)")).Text, Is.EqualTo("Roberto"));
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(7)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) .delete-icon path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) .delete-icon path"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(7)")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) .delete-icon path")).Click();
    driver.FindElement(By.CssSelector(".pb-3")).Click();
    driver.FindElement(By.LinkText("Voltar para a lista")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) .delete-icon path")).Click();
    driver.FindElement(By.CssSelector(".alert")).Click();
    driver.FindElement(By.CssSelector(".container:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h3")).Text, Is.EqualTo("Tem certeza que deseja excluir?"));
    driver.FindElement(By.CssSelector(".row")).Click();
    driver.FindElement(By.CssSelector(".col-sm-10:nth-child(4)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-10:nth-child(4)")).Text, Is.EqualTo("21/05/2026 10:30"));
    driver.FindElement(By.CssSelector(".col-sm-10:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-10:nth-child(6)")).Text, Is.EqualTo("21/05/2026 11:00"));
    driver.FindElement(By.CssSelector(".col-sm-10:nth-child(8)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-10:nth-child(8)")).Text, Is.EqualTo("Suspensão curta"));
    driver.FindElement(By.CssSelector(".col-sm-10:nth-child(10)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-10:nth-child(10)")).Text, Is.EqualTo("Uso de celular em sala de aula"));
    driver.FindElement(By.CssSelector(".col-sm-10:nth-child(12)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-10:nth-child(12)")).Text, Is.EqualTo("2"));
    driver.FindElement(By.CssSelector(".col-sm-10:nth-child(14)")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".col-sm-10:nth-child(14)")).Text, Is.EqualTo("6"));
    {
      var element = driver.FindElement(By.CssSelector(".btn-danger"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".btn-danger"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".btn-danger"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
    driver.FindElement(By.CssSelector("body")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(1)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(1)")).Text, Is.EqualTo("22/05/2026 14:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(2)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(2)")).Text, Is.EqualTo("22/05/2026 15:00"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Text, Is.EqualTo("Advertência"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(4)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(4)")).Text, Is.EqualTo("Falta não justificada"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(5)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(5)")).Text, Is.EqualTo("Ana"));
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(6)")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(6)")).Text, Is.EqualTo("Roberto"));
  }
}
